version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: system_metrics_db
    environment:
      POSTGRES_DB: system_metrics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - metrics_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d system_metrics"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: dockerfile
    container_name: system_metrics_frontend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=system_metrics
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - BACKEND_URL=http://host.docker.internal:8080
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  metrics_data:
    name: metrics_data