version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: metrics-postgres
    environment:
      POSTGRES_DB: metrics_db
      POSTGRES_USER: metrics_202201947
      POSTGRES_PASSWORD: metrics_202201947
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metrics_202201947 -d metrics_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local